# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts
COPY . .
CMD ["node", "server-stdio.js"]
